# name: orders-manager-php-dev
services:
  mysql:
    image: mysql:5.7
    container_name: orders-man-php-dev_mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - type: bind
        source: ./mysql/backup.sql
        target: /docker-entrypoint-initdb.d/backup.sql
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    networks:
      - localnet

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: orders-man-php-dev_phpmyadmin
    ports:
      - "81-90:80"
    environment:
      - PMA_HOST
    networks:
      - localnet

  php-app:
    depends_on:
      - mysql
    container_name: orders-man-php-dev_php-app
    build:
      context: ./php-app
      dockerfile: dev.Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: ./
        target: /orders-manager-php
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - PHP_APP_SRC
    networks:
      - localnet

volumes:
  mysql-data:


networks:
  localnet:
    driver: bridge
